import { strict as assert } from "node:assert";
import { test } from "node:test";
import { addColumnSql, alterColumnSql, blankSpec, defaultSql, type ColumnSpec } from "./column-statements.ts";
import { readColumnFacts, readColumnSpec } from "./column-facts.ts";

const TYPES = ["text", "int4", "int8", "uuid", "timestamptz"];
const ctx = { pkName: "t_pkey", pkColumns: ["a"], uniqueName: null, checkName: null };
const col = (patch: Partial<ColumnSpec>): ColumnSpec => ({ ...blankSpec(), name: "c", ...patch });

test("a default in brackets runs as written; anything else is a quoted literal", () => {
  assert.equal(defaultSql("(gen_random_uuid())"), "(gen_random_uuid())");
  assert.equal(defaultSql("it's"), "'it''s'");
  assert.equal(defaultSql("  "), null);
});

test("a new column carries everything inline, then its key, its foreign key and its comment", () => {
  const sql = addColumnSql("public", "t", col({
    type: "int8", nullable: false, unique: true, check: "c > 0", default: "1", primary: true, comment: "count",
    foreignKeys: [{ name: null, schema: "public", table: "p", column: "id", onUpdate: "a", onDelete: "c" }],
  }), ctx, TYPES);
  assert.equal(sql, [
    `alter table "public"."t"`,
    `  add column "c" int8 default '1' not null unique check (c > 0),`,
    `  drop constraint "t_pkey",`,
    `  add primary key ("a", "c"),`,
    `  add foreign key ("c") references "public"."p" ("id") on update no action on delete cascade;`,
    `comment on column "public"."t"."c" is 'count';`,
  ].join("\n"));
});

test("an edit sends only what changed, and renames last", () => {
  const before = col({ type: "int4", default: "(0)", nullable: true });
  assert.equal(alterColumnSql("public", "t", before, { ...before, comment: "x" }, ctx, TYPES), `comment on column "public"."t"."c" is 'x';`);
  const sql = alterColumnSql("public", "t", before, { ...before, type: "int8", name: "d" }, ctx, TYPES).split("\n");
  assert.deepEqual(sql, [`alter table "public"."t"`, `  alter column "c" type int8;`, `alter table "public"."t" rename column "c" to "d";`]);
  assert.throws(() => alterColumnSql("public", "t", before, { ...before }, ctx, TYPES), /Nothing has changed/);
});

test("becoming an identity drops the default and sets not null first, then moves the sequence", () => {
  const before = col({ type: "int4", default: "(0)", nullable: true });
  const sql = alterColumnSql("public", "t", before, { ...before, default: "", nullable: false, identity: true }, ctx, TYPES);
  const lines = sql.split("\n");
  assert.ok(lines.indexOf(`  alter column "c" set not null,`) < lines.indexOf(`  alter column "c" add generated by default as identity;`));
  assert.match(sql, /drop default/);
  assert.match(sql, /setval\(pg_catalog\.pg_get_serial_sequence\('"public"\."t"', 'c'\), m\)/);
  assert.throws(() => alterColumnSql("public", "t", before, { ...before, identity: true }, ctx, TYPES), /cannot also have a default|cannot allow null/);
});

test("taking a column out of a composite key keeps the rest of it", () => {
  const before = col({ primary: true, nullable: false });
  const sql = alterColumnSql("public", "t", before, { ...before, primary: false }, { ...ctx, pkColumns: ["a", "c"] }, TYPES);
  assert.match(sql, /drop constraint "t_pkey",\n {2}add primary key \("a"\);/);
});

test("unique and check drop by the names the catalog gave them", () => {
  const before = col({ unique: true, check: "c <> ''" });
  const named = { ...ctx, uniqueName: "t_c_key", checkName: "t_c_check" };
  const sql = alterColumnSql("public", "t", before, { ...before, unique: false, check: "length(c) < 9" }, named, TYPES);
  assert.match(sql, /drop constraint "t_c_key"/);
  assert.match(sql, /drop constraint "t_c_check",\n {2}add check \(length\(c\) < 9\)/);
});

test("a foreign key whose action changed is dropped and added back; one removed is only dropped", () => {
  const fk = { name: "t_c_fkey", schema: "public", table: "p", column: "id", onUpdate: "a" as const, onDelete: "c" as const };
  const before = col({ foreignKeys: [fk] });
  assert.match(alterColumnSql("public", "t", before, { ...before, foreignKeys: [{ ...fk, onDelete: "n" }] }, ctx, TYPES), /drop constraint "t_c_fkey",\n {2}add foreign key .* on delete set null;/);
  assert.equal(alterColumnSql("public", "t", before, { ...before, foreignKeys: [] }, ctx, TYPES), `alter table "public"."t"\n  drop constraint "t_c_fkey";`);
});

test("what the browser posts is checked field by field", () => {
  assert.ok(readColumnSpec(col({})));
  assert.equal(readColumnSpec({ ...col({}), nullable: "yes" }), null);
  assert.equal(readColumnSpec({ ...col({}), foreignKeys: [{ schema: "p", table: "t", column: "id", onUpdate: "x", onDelete: "a" }] }), null);
  assert.equal(readColumnSpec(null), null);
});

test("the catalog's answer becomes the panel's before, a stored default in brackets", () => {
  const facts = readColumnFacts({
    found: true, pkName: "t_pkey", pkColumns: ["id"],
    column: { name: "id", type: "int8", default: "nextval('s'::regclass)", nullable: false, check: { name: "k", expr: "(id > 0)" } },
  });
  assert.equal(facts.column?.primary, true);
  assert.equal(facts.column?.default, "(nextval('s'::regclass))");
  assert.equal(facts.column?.check, "id > 0");
  assert.equal(facts.checkName, "k");
  assert.equal(readColumnFacts({ found: true, column: null }).column, null);
});
