// Explicit .ts extensions: reached from a node:test file, as `ddl-statements.ts` is.
import { quoteIdent, quoteLiteral, quoteQualified } from "./sql-ident.ts";
import { checkName, checkType, IDENTITY_TYPES } from "./ddl-build.ts";

/** `pg_constraint.confupdtype` / `confdeltype` codes, and what each one reads as in a statement. */
export const FK_ACTIONS = [
  { code: "a", label: "No action", sql: "no action" },
  { code: "r", label: "Restrict", sql: "restrict" },
  { code: "c", label: "Cascade", sql: "cascade" },
  { code: "n", label: "Set null", sql: "set null" },
  { code: "d", label: "Set default", sql: "set default" },
] as const;
export type FkAction = (typeof FK_ACTIONS)[number]["code"];
const actionSql = (code: FkAction) => FK_ACTIONS.find((a) => a.code === code)!.sql;

/** One single-column foreign key. `name` is null for one that does not exist yet. */
export type ForeignKey = { name: string | null; schema: string; table: string; column: string; onUpdate: FkAction; onDelete: FkAction };

/** Everything the original's column panel edits, bar Data Privacy. */
export type ColumnSpec = {
  name: string;
  comment: string;
  /** The element type's `typname`, checked against the catalog list. */
  type: string;
  array: boolean;
  identity: boolean;
  /** The original's rule: `(expr)` in brackets runs as written, anything else is a quoted literal. */
  default: string;
  nullable: boolean;
  primary: boolean;
  unique: boolean;
  check: string;
  foreignKeys: ForeignKey[];
};

/** The table-level facts a column change depends on, read by the server when it runs. */
export type ColumnContext = {
  pkName: string | null;
  pkColumns: string[];
  uniqueName: string | null;
  checkName: string | null;
};

export const blankSpec = (): ColumnSpec => ({
  name: "", comment: "", type: "text", array: false, identity: false, default: "",
  nullable: true, primary: false, unique: false, check: "", foreignKeys: [],
});

export function defaultSql(value: string): string | null {
  const v = value.trim();
  if (!v) return null;
  return /^\(.*\)$/s.test(v) ? v : quoteLiteral(v);
}

const typeSql = (s: ColumnSpec, allowed: string[]) => {
  checkType(s.type, allowed);
  return `${s.type}${s.array ? "[]" : ""}`;
};

function checkIdentity(s: ColumnSpec) {
  if (!s.identity) return;
  if (s.array || !IDENTITY_TYPES.has(s.type)) throw new Error("Only an integer column can be an identity");
  if (s.default.trim()) throw new Error("An identity column generates its own value, so it cannot also have a default");
  // Measured: adding one to a nullable column answers "must be declared NOT NULL before identity".
  if (s.nullable) throw new Error("An identity column cannot allow null");
}

const fkClause = (column: string, k: ForeignKey) => {
  checkName(k.schema, "schema name");
  checkName(k.table, "table name");
  checkName(k.column, "column name");
  return (
    `add foreign key (${quoteIdent(column)}) references ${quoteQualified(k.schema, k.table)} (${quoteIdent(k.column)})` +
    ` on update ${actionSql(k.onUpdate)} on delete ${actionSql(k.onDelete)}`
  );
};

/** Drop the table's key and add it back with `columns` — in one statement, so it is never missing. */
const pkParts = (pkName: string | null, columns: string[]) => [
  ...(pkName ? [`drop constraint ${quoteIdent(pkName)}`] : []),
  ...(columns.length ? [`add primary key (${columns.map(quoteIdent).join(", ")})`] : []),
];

const alterTable = (target: string, parts: string[]) => `alter table ${target}\n  ${parts.join(",\n  ")};`;

/** A new column, with everything the panel says about it, as one `alter table` and its comment. */
export function addColumnSql(schema: string, table: string, s: ColumnSpec, ctx: ColumnContext, allowed: string[]): string {
  checkName(s.name, "column name");
  checkIdentity(s);
  const target = quoteQualified(schema, table);
  const col = quoteIdent(s.name);
  const def = defaultSql(s.default);

  const clause = [
    col,
    typeSql(s, allowed),
    s.identity ? "generated by default as identity" : null,
    def ? `default ${def}` : null,
    s.nullable ? null : "not null",
    s.unique ? "unique" : null,
    s.check.trim() ? `check (${s.check.trim()})` : null,
  ].filter(Boolean);

  const parts = [`add column ${clause.join(" ")}`];
  if (s.primary) parts.push(...pkParts(ctx.pkName, [...ctx.pkColumns, s.name]));
  for (const k of s.foreignKeys) parts.push(fkClause(s.name, k));

  const out = [alterTable(target, parts)];
  if (s.comment.trim()) out.push(`comment on column ${target}.${col} is ${quoteLiteral(s.comment.trim())};`);
  return out.join("\n");
}

const sameKey = (a: ForeignKey, b: ForeignKey) =>
  a.schema === b.schema && a.table === b.table && a.column === b.column && a.onUpdate === b.onUpdate && a.onDelete === b.onDelete;

/**
 * An existing column, `before` → `after`. Only what changed, in one `alter table` so every part
 * lands or none does; the comment after it and the rename last, so everything before names the
 * column as it still is.
 */
export function alterColumnSql(
  schema: string,
  table: string,
  before: ColumnSpec,
  after: ColumnSpec,
  ctx: ColumnContext,
  allowed: string[],
): string {
  checkIdentity(after);
  const target = quoteQualified(schema, table);
  const col = quoteIdent(before.name);
  const parts: string[] = [];

  if (after.type !== before.type || after.array !== before.array) {
    parts.push(`alter column ${col} type ${typeSql(after, allowed)}`);
  }
  // An identity cannot coexist with a default: drop one before the other arrives.
  if (before.identity && !after.identity) parts.push(`alter column ${col} drop identity`);
  if (after.default.trim() !== before.default.trim()) {
    const def = defaultSql(after.default);
    parts.push(def ? `alter column ${col} set default ${def}` : `alter column ${col} drop default`);
  }
  // Not null before identity: Postgres checks for it when the identity is added.
  if (after.nullable !== before.nullable) parts.push(`alter column ${col} ${after.nullable ? "drop" : "set"} not null`);
  if (!before.identity && after.identity) parts.push(`alter column ${col} add generated by default as identity`);

  if (after.unique !== before.unique) {
    if (after.unique) parts.push(`add unique (${col})`);
    else if (ctx.uniqueName) parts.push(`drop constraint ${quoteIdent(ctx.uniqueName)}`);
    else throw new Error("The unique constraint on this column could not be found");
  }
  if (after.check.trim() !== before.check.trim()) {
    if (ctx.checkName) parts.push(`drop constraint ${quoteIdent(ctx.checkName)}`);
    if (after.check.trim()) parts.push(`add check (${after.check.trim()})`);
  }
  if (after.primary !== before.primary) {
    const columns = after.primary ? [...ctx.pkColumns, before.name] : ctx.pkColumns.filter((c) => c !== before.name);
    parts.push(...pkParts(ctx.pkName, columns));
  }

  const kept = new Map(after.foreignKeys.filter((k) => k.name).map((k) => [k.name, k]));
  for (const k of before.foreignKeys) {
    const next = k.name ? kept.get(k.name) : undefined;
    if (next && sameKey(k, next)) continue;
    parts.push(`drop constraint ${quoteIdent(k.name!)}`);
    if (next) parts.push(fkClause(before.name, next));
  }
  for (const k of after.foreignKeys.filter((k) => !k.name)) parts.push(fkClause(before.name, k));

  const out = parts.length ? [alterTable(target, parts)] : [];
  // A new identity's sequence starts at 1 over rows that already hold values — measured: the next
  // insert took 1 beside an existing 1. Moved past the maximum, as a duplicate's is.
  if (!before.identity && after.identity) {
    out.push(
      `select pg_catalog.setval(pg_catalog.pg_get_serial_sequence(${quoteLiteral(target)}, ${quoteLiteral(before.name)}), m) ` +
        `from (select max(${col}) as m from ${target}) s where m is not null;`,
    );
  }
  if (after.comment.trim() !== before.comment.trim()) {
    out.push(`comment on column ${target}.${col} is ${after.comment.trim() ? quoteLiteral(after.comment.trim()) : "null"};`);
  }
  if (after.name !== before.name) {
    checkName(after.name, "column name");
    out.push(`alter table ${target} rename column ${col} to ${quoteIdent(after.name)};`);
  }

  if (out.length === 0) throw new Error("Nothing has changed");
  return out.join("\n");
}
