// Explicit .ts extensions, unlike the rest of lib/: this module is reached from a node:test file,
// and Node's resolver has no bundler to fall back on. Do not "tidy" them away.
import { quoteIdent, quoteLiteral } from "./sql-ident.ts";

/**
 * The pieces DDL is built from. The statements themselves are in `ddl-statements.ts`.
 *
 * The construction that makes B1 safe does not apply here. Values travel as one JSON literal and are
 * unpacked by `jsonb_to_record`; a table name, a column name and a type name are none of those — they
 * are grammar, and grammar cannot be sent as data. So each input gets its own discipline instead:
 *
 * - **Names** go through `quoteIdent`, whose only escape is doubling an interior quote. A hostile
 *   name stays one identifier.
 * - **Type names** are matched against a list read from `pg_type` at request time. A name not on it
 *   is refused, never quoted in — quoting a type name does not make an unknown one safe, it makes it
 *   an unknown one in quotes.
 * - **Defaults** are executable by design and cannot be escaped at all. A default therefore says
 *   which kind it is, and `raw` is only ever passed by a caller whose UI labels the field as SQL.
 */

/** Offered first in a type picker. The rest of the catalog list sits behind a search. */
export const COMMON_TYPES = [
  "text",
  "int8",
  "int4",
  "bool",
  "uuid",
  "timestamptz",
  "jsonb",
  "numeric",
  "date",
  "float8",
];

/** The whole fixed list a new column may choose from. Anything else has to be typed as SQL later. */
export const DEFAULT_EXPRESSIONS = ["now()", "gen_random_uuid()", "auth.uid()", "true", "false"];

/** Only an integer column can be an identity. */
export const IDENTITY_TYPES = new Set(["int2", "int4", "int8", "smallint", "integer", "bigint"]);

export type ColumnDefault =
  /** From `DEFAULT_EXPRESSIONS`, and checked against it. Interpolated as written, because it runs. */
  | { kind: "expression"; value: string }
  /** A plain value, quoted as a literal. */
  | { kind: "literal"; value: string }
  /** Free SQL. Only from a field the user was told is SQL, and only after they saw the statement. */
  | { kind: "raw"; value: string };

export type NewColumn = {
  name: string;
  /** A `pg_type.typname`, checked against the catalog list. */
  type: string;
  nullable: boolean;
  primaryKey: boolean;
  identity?: boolean;
  default?: ColumnDefault | null;
};

export type ColumnChange = {
  rename?: string;
  type?: string;
  nullable?: boolean;
  default?: ColumnDefault | null | "drop";
};

/**
 * NAMEDATALEN is 63 **bytes**, not characters.
 *
 * Postgres truncates a longer identifier and only raises a NOTICE, so the table it creates is not
 * the one the preview showed. Measured: a 32-character CJK name (96 bytes) came back as 21
 * characters. Counting characters would have let all 32 through.
 */
export function checkName(name: string, what: string) {
  // Whitespace-only is refused; whitespace *around* a name is not, because it is a legal identifier
  // and the preview quotes it, so nothing is hidden. Trimming would change what was typed.
  if (name.trim() === "") throw new Error(`A ${what} cannot be empty`);
  const bytes = new TextEncoder().encode(name).length;
  if (bytes > 63) {
    throw new Error(
      `A ${what} cannot be longer than 63 bytes; this one is ${bytes}. ` +
        `Postgres would shorten it silently.`,
    );
  }
}

export function checkType(type: string, allowed: string[]) {
  if (!allowed.includes(type)) {
    throw new Error(`Unknown type: ${type}. Types come from the database's own list.`);
  }
}

export function defaultClause(d: ColumnDefault): string {
  if (d.kind === "expression") {
    if (!DEFAULT_EXPRESSIONS.includes(d.value)) {
      throw new Error(`${d.value} is not one of the offered defaults`);
    }
    return d.value;
  }
  return d.kind === "literal" ? quoteLiteral(d.value) : d.value;
}

/** `"name" type [identity] [default …] [not null]` — the shape both create and add need. */
export function columnClause(c: NewColumn, allowed: string[]): string {
  checkName(c.name, "column name");
  checkType(c.type, allowed);
  if (c.identity && !IDENTITY_TYPES.has(c.type)) {
    throw new Error(`${c.name} is ${c.type}; only an integer column can be an identity`);
  }
  // An identity column generates its own value, so a DEFAULT beside it is a contradiction Postgres
  // rejects — better to say which of the two the caller meant than to pass it on.
  if (c.identity && c.default) {
    throw new Error(`${c.name} is an identity column and cannot also have a default`);
  }

  return [
    quoteIdent(c.name),
    c.type,
    c.identity ? "generated by default as identity" : null,
    c.default ? `default ${defaultClause(c.default)}` : null,
    c.nullable ? null : "not null",
  ]
    .filter(Boolean)
    .join(" ");
}
