import assert from "node:assert/strict";
import test from "node:test";
import {
  createTable,
  dropColumn,
  dropTable,
  setRls,
} from "./ddl-statements.ts";
import type { NewColumn } from "./ddl-build.ts";

const TYPES = ["text", "int4", "int8", "bool", "uuid", "timestamptz", "jsonb", "numeric"];

const c = (name: string, type = "text", over: Partial<NewColumn> = {}): NewColumn => ({
  name,
  type,
  nullable: true,
  primaryKey: false,
  ...over,
});

// --- create ---

test("creates a table with quoted names, a primary key and nullability", () => {
  const sql = createTable(
    "public",
    "MyTable",
    [c("id", "int8", { primaryKey: true, nullable: false, identity: true }), c("order")],
    TYPES,
    { rls: false },
  );
  assert.ok(sql.startsWith('create table "public"."MyTable" ('));
  assert.ok(sql.includes('"id" int8 generated by default as identity not null'));
  assert.ok(sql.includes('"order" text'));
  assert.ok(sql.includes('primary key ("id")'));
});

test("a mixed-case name and a reserved word survive because they are quoted", () => {
  // Unquoted, `MyTable` folds to lowercase and `order` is a syntax error — quoting is not only
  // injection defence here.
  const sql = createTable("public", "MyTable", [c("order")], TYPES, { rls: false });
  assert.ok(sql.includes('"MyTable"'));
  assert.ok(sql.includes('"order"'));
});

test("RLS is enabled in the same request, not a second round trip", () => {
  const sql = createTable("public", "t", [c("a")], TYPES, { rls: true });
  assert.ok(sql.includes('alter table "public"."t" enable row level security;'));
  assert.ok(sql.indexOf("create table") < sql.indexOf("enable row level security"));
});

test("a composite primary key names every column, in order", () => {
  const sql = createTable(
    "public",
    "t",
    [c("a", "int4", { primaryKey: true }), c("b", "int4", { primaryKey: true }), c("z")],
    TYPES,
    { rls: false },
  );
  assert.ok(sql.includes('primary key ("a", "b")'));
});

test("a table with no columns is refused", () => {
  assert.throws(() => createTable("public", "t", [], TYPES, { rls: false }), /at least one column/i);
});

test("an empty or over-long name is refused", () => {
  assert.throws(() => createTable("public", "  ", [c("a")], TYPES, { rls: false }), /cannot be empty/i);
  const long = "x".repeat(64);
  assert.throws(() => createTable("public", long, [c("a")], TYPES, { rls: false }), /63 bytes/);
});

test("the 63 limit is measured in bytes, which is what Postgres truncates on", () => {
  // Measured live: a 32-character CJK name (96 bytes) was created as 21 characters, with only a
  // NOTICE. Counting characters would have let it through and the preview would have shown a table
  // name that does not exist.
  const cjk = "顧客マスタ管理用一時テーブル対象".repeat(2);
  assert.equal([...cjk].length, 32);
  assert.equal(new TextEncoder().encode(cjk).length, 96);
  assert.throws(() => createTable("public", cjk, [c("a")], TYPES, { rls: false }), /96/);

  // 63 ASCII characters is still fine, and so is a multi-byte name that fits.
  assert.ok(createTable("public", "x".repeat(63), [c("a")], TYPES, { rls: false }));
  assert.ok(createTable("public", "顧客", [c("a")], TYPES, { rls: false }));
});

test("a duplicate column name is refused rather than left to Postgres", () => {
  assert.throws(
    () => createTable("public", "t", [c("a"), c("a", "int4")], TYPES, { rls: false }),
    /duplicate/i,
  );
});

// --- types ---

test("a type that is not on the catalog list is refused, not quoted in", () => {
  // Quoting a type name does not make an unknown one safe; it makes it an unknown one in quotes.
  assert.throws(() => createTable("public", "t", [c("a", "hstore")], TYPES, { rls: false }), /Unknown type/);
  assert.throws(
    () => createTable("public", "t", [c("a", "text; drop table x")], TYPES, { rls: false }),
    /Unknown type/,
  );
});

test("only an integer column can be an identity", () => {
  assert.throws(
    () => createTable("public", "t", [c("a", "text", { identity: true })], TYPES, { rls: false }),
    /only an integer column/i,
  );
});

test("an identity column cannot also carry a default", () => {
  assert.throws(
    () =>
      createTable(
        "public",
        "t",
        [c("a", "int8", { identity: true, default: { kind: "expression", value: "now()" } })],
        TYPES,
        { rls: false },
      ),
    /cannot also have a default/i,
  );
});

// --- defaults ---

test("an offered default is written as it stands, because it runs", () => {
  const sql = createTable(
    "public",
    "t",
    [c("at", "timestamptz", { default: { kind: "expression", value: "now()" } })],
    TYPES,
    { rls: false },
  );
  assert.ok(sql.includes("default now()"));
});

test("an expression outside the offered list is refused", () => {
  assert.throws(
    () =>
      createTable(
        "public",
        "t",
        [c("a", "text", { default: { kind: "expression", value: "pg_read_file('/etc/passwd')" } })],
        TYPES,
        { rls: false },
      ),
    /not one of the offered defaults/i,
  );
});

test("a literal default is quoted, so a quote in it cannot end the string", () => {
  const sql = createTable(
    "public",
    "t",
    [c("a", "text", { default: { kind: "literal", value: "it's '; drop table x; --" } })],
    TYPES,
    { rls: false },
  );
  assert.ok(sql.includes(`default 'it''s ''; drop table x; --'`));
});

// --- identifiers ---

test("a hostile name stays inside one quoted identifier", () => {
  const evil = `x"; drop table users; --`;
  const sql = createTable("public", "t", [c(evil)], TYPES, { rls: false });
  assert.ok(sql.includes(`"x""; drop table users; --"`));
  assert.ok(!sql.includes("; drop table users; --\n"), "the injection never leaves the quotes");
});

test("a backslash in a name is left alone, since the endpoint passes them through unchanged", () => {
  // Measured: N backslashes in the request arrive as N characters, in literals and identifiers
  // alike. Doubling them here would create a column with a different name than the preview showed.
  const sql = createTable("public", "t", [c("a\\b")], TYPES, { rls: false });
  assert.ok(sql.includes('"a\\b"'));
});

// --- add, alter, drop ---

test("the last column cannot be dropped", () => {
  // Postgres refuses this too, but only after the confirmation has promised it.
  assert.throws(() => dropColumn("public", "t", "a", 1), /at least one column/i);
  assert.ok(dropColumn("public", "t", "a", 2).includes('drop column "a"'));
});

test("drop table and the RLS toggle name the table both ways", () => {
  assert.equal(dropTable("public", "My t"), 'drop table "public"."My t";');
  assert.ok(setRls("public", "t", true).endsWith("enable row level security;"));
  assert.ok(setRls("public", "t", false).endsWith("disable row level security;"));
});
