// Explicit .ts extensions, unlike the rest of lib/: this module is imported directly by a node:test
// file, and Node's resolver has no bundler to fall back on. Do not "tidy" them away.
import { quoteIdent } from "./sql-ident.ts";
import { isTruncated, type ColumnInfo } from "./table-view.ts";

/**
 * Building INSERT, UPDATE and DELETE without bind parameters.
 *
 * The Management API's query endpoint takes SQL as text. Rather than quoting every value — N chances
 * to be wrong — all of them travel as **one** JSON literal, dollar-quoted with a random tag, and
 * Postgres unpacks it with `jsonb_to_record`. `JSON.stringify` is a well-tested encoder, and the
 * result crosses into SQL at exactly one boundary whose safety is a single checkable property: the
 * tag does not occur in the encoded string.
 *
 * Column types for the record list come from the catalog, so Postgres does the coercion rather than
 * this module guessing at it.
 */

export type Row = Record<string, unknown>;

/**
 * A statement that is known to end in RETURNING, because the builder that made it said so.
 *
 * `execute` accepts only this. Testing the SQL text for the word "returning" cannot work: the JSON
 * payload is embedded in that same string, so a row value containing it would satisfy the check —
 * a guard whose verdict depends on user data is not a guard.
 */
export type Statement = { sql: string; returning: string[] };

/**
 * Values the grid shortened for display must never travel back into the database.
 *
 * `table-rows.ts` truncates wide types at 512 characters in SQL and appends an ellipsis. Writing
 * that back replaces the real value with a shortened one — silently, with `affected: 1`, and with no
 * undo. `bytea` is the worst case: a cut `\x…` string is still valid input, so it would store a
 * value that is well-formed and wrong.
 */
export function rejectTruncated(rows: Row[]) {
  for (const row of rows) {
    for (const [name, value] of Object.entries(row)) {
      if (isTruncated(value)) {
        throw new Error(
          `The value in "${name}" was shortened for display and cannot be written back. ` +
            `Open the row detail to load it in full.`,
        );
      }
    }
  }
}

/** Wraps a value as one dollar-quoted JSON literal, with a tag proven absent from the encoding. */
export function jsonLiteral(value: unknown): { sql: string; tag: string } {
  const json = JSON.stringify(value);
  let tag: string;
  // Generated, then *verified*. The randomness only makes the first attempt likely to succeed; the
  // check is what makes it safe, and a tag generated but never checked is a bug that hides in testing.
  do {
    tag = `sdb${Math.random().toString(36).slice(2, 12)}`;
  } while (json.includes(`$${tag}$`));
  return { sql: `$${tag}$${json}$${tag}$`, tag };
}

const byName = (columns: ColumnInfo[]) => new Map(columns.map((c) => [c.name, c]));

/** `"a" integer, "b" jsonb` — the shape `jsonb_to_record` needs to coerce each field. */
export function recordList(columns: ColumnInfo[], names: string[]): string {
  return names.map((n) => `${quoteIdent(n)} ${columns.find((c) => c.name === n)!.data_type}`).join(", ");
}

export function checkKnown(columns: ColumnInfo[], names: string[]) {
  const known = byName(columns);
  for (const n of names) {
    if (!known.has(n)) throw new Error(`Unknown column: ${n}`);
  }
}

/**
 * Identity and stored generated columns can be read but never written.
 *
 * Only the columns a statement *writes* — never the key. An identity primary key is the ordinary
 * Supabase shape, and it has to stay usable to address a row.
 */
export function rejectGenerated(columns: ColumnInfo[], names: string[]) {
  const known = byName(columns);
  for (const n of names) {
    if (known.get(n)?.generated) {
      throw new Error(`"${n}" is generated by the database and cannot be written`);
    }
  }
}

export const primaryKey = (columns: ColumnInfo[]) =>
  columns.filter((c) => c.pk_pos != null).sort((a, b) => (a.pk_pos ?? 0) - (b.pk_pos ?? 0));

export function returningKey(columns: ColumnInfo[], prefix = ""): string {
  const pk = primaryKey(columns);
  if (pk.length === 0) throw new Error("Table has no primary key, so a write cannot be confirmed");
  return pk.map((c) => `${prefix}${quoteIdent(c.name)}`).join(", ");
}
